### ISSUE TITLE
error on compile (windows)

### ISSUE THREAD

**Issue by Gawaboumgaa** [lqt5/lqt#5]
I can't use lqt because of this error:  https://hastebin.com/ribecudema.sql

**Comment by sanikoyes** [comment]
I was tested msvc2017 on win7/win10 platform with qt 5.12.0/5.13.0
what version of your windows, msvc, qt?

**Comment by Gawaboumgaa** [comment]
msvc2017 on windows 10 with qt 5.13

**Comment by Gawaboumgaa** [comment]
I tried with Win32 and here is the result, errors in the files apparently : https://hastebin.com/utiviyujas.m

**Comment by sanikoyes** [comment]
It seems that you should have not executed the following command:
```
git submodule update --init --recursive --remote
```
Have written on the compilation steps, :D

**Comment by leonardus** [comment]
I've run that command (`git submodule update --init --recursive --remote`) but still get these errors: https://gist.github.com/leonardus/0fe7baefcae66556ae14df3068319bde

**Comment by sanikoyes** [comment]
> I've run that command (`git submodule update --init --recursive --remote`) but still get these errors: https://gist.github.com/leonardus/0fe7baefcae66556ae14df3068319bde

Lqt does not support x86 cpu model. Add `Win64` for cmake:
cmake -G "Visual Studio 15 2017 Win64" -H. -Bbuild

**Comment by sanikoyes** [comment]
Close
